version: "3"
networks:
  backend:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - backend

  mysql:
    image: mysql:8
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - backend

  # node
  node-service:
    image: node:latest
    volumes:
      - ./app:/var/www/project
    working_dir: /var/www/project
    networks:
      - backend