security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        register:
            pattern: ^/api/register
            stateless: true
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                username_path: email
                check_path: api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            refresh_jwt:
                check_path: api_refresh_token
        api:
            pattern: ^/api/home
            stateless: true
            provider: app_user_provider
            jwt: ~
            logout:
                path: api_token_invalidate
        main:
            remote_user:
                provider: app_user_provider

    access_control:
        - { path: ^/api/register,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login,             roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/home,              roles: IS_AUTHENTICATED_FULLY }